/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UploadImagesResponse } from '../../models/upload-images-response';

export interface ApiSitesSiteNanoidImagesPost$Plain$Params {
  siteNanoid: string;
      body?: {
'files'?: Array<Blob>;
}
}

export function apiSitesSiteNanoidImagesPost$Plain(http: HttpClient, rootUrl: string, params: ApiSitesSiteNanoidImagesPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<UploadImagesResponse>> {
  const rb = new RequestBuilder(rootUrl, apiSitesSiteNanoidImagesPost$Plain.PATH, 'post');
  if (params) {
    rb.path('siteNanoid', params.siteNanoid, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UploadImagesResponse>;
    })
  );
}

apiSitesSiteNanoidImagesPost$Plain.PATH = '/api/sites/{siteNanoid}/images';
