/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SiteImageResponse } from '../../models/site-image-response';

export interface ApiSitesSiteNanoidImagesGet$Json$Params {
  siteNanoid: string;
}

export function apiSitesSiteNanoidImagesGet$Json(http: HttpClient, rootUrl: string, params: ApiSitesSiteNanoidImagesGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SiteImageResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiSitesSiteNanoidImagesGet$Json.PATH, 'get');
  if (params) {
    rb.path('siteNanoid', params.siteNanoid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SiteImageResponse>>;
    })
  );
}

apiSitesSiteNanoidImagesGet$Json.PATH = '/api/sites/{siteNanoid}/images';
