/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiSitesSiteNanoidImagesFileNameGet$Params {
  siteNanoid: string;
  fileName: string;
  version?: string;
}

export function apiSitesSiteNanoidImagesFileNameGet(http: HttpClient, rootUrl: string, params: ApiSitesSiteNanoidImagesFileNameGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiSitesSiteNanoidImagesFileNameGet.PATH, 'get');
  if (params) {
    rb.path('siteNanoid', params.siteNanoid, {});
    rb.path('fileName', params.fileName, {});
    rb.query('version', params.version, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiSitesSiteNanoidImagesFileNameGet.PATH = '/api/sites/{siteNanoid}/images/{fileName}';
