/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HealthResponse } from '../../models/health-response';

export interface HealthGet$Plain$Params {
}

export function healthGet$Plain(http: HttpClient, rootUrl: string, params?: HealthGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<HealthResponse>> {
  const rb = new RequestBuilder(rootUrl, healthGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<HealthResponse>;
    })
  );
}

healthGet$Plain.PATH = '/health';
