/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DomainResponse } from '../../models/domain-response';

export interface ApiSitesSiteNanoidDomainsGet$Plain$Params {
  siteNanoid: string;
}

export function apiSitesSiteNanoidDomainsGet$Plain(http: HttpClient, rootUrl: string, params: ApiSitesSiteNanoidDomainsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DomainResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiSitesSiteNanoidDomainsGet$Plain.PATH, 'get');
  if (params) {
    rb.path('siteNanoid', params.siteNanoid, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DomainResponse>>;
    })
  );
}

apiSitesSiteNanoidDomainsGet$Plain.PATH = '/api/sites/{siteNanoid}/domains';
