/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddDomainRequest } from '../../models/add-domain-request';
import { DomainResponse } from '../../models/domain-response';

export interface ApiSitesSiteNanoidDomainsPost$Plain$Params {
  siteNanoid: string;
      body?: AddDomainRequest
}

export function apiSitesSiteNanoidDomainsPost$Plain(http: HttpClient, rootUrl: string, params: ApiSitesSiteNanoidDomainsPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DomainResponse>> {
  const rb = new RequestBuilder(rootUrl, apiSitesSiteNanoidDomainsPost$Plain.PATH, 'post');
  if (params) {
    rb.path('siteNanoid', params.siteNanoid, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DomainResponse>;
    })
  );
}

apiSitesSiteNanoidDomainsPost$Plain.PATH = '/api/sites/{siteNanoid}/domains';
