/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DomainResponse } from '../../models/domain-response';

export interface ApiSitesSiteNanoidDomainsDomainNanoidCheckPost$Json$Params {
  siteNanoid: string;
  domainNanoid: string;
}

export function apiSitesSiteNanoidDomainsDomainNanoidCheckPost$Json(http: HttpClient, rootUrl: string, params: ApiSitesSiteNanoidDomainsDomainNanoidCheckPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DomainResponse>> {
  const rb = new RequestBuilder(rootUrl, apiSitesSiteNanoidDomainsDomainNanoidCheckPost$Json.PATH, 'post');
  if (params) {
    rb.path('siteNanoid', params.siteNanoid, {});
    rb.path('domainNanoid', params.domainNanoid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DomainResponse>;
    })
  );
}

apiSitesSiteNanoidDomainsDomainNanoidCheckPost$Json.PATH = '/api/sites/{siteNanoid}/domains/{domainNanoid}/check';
