/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiSitesSiteNanoidSubmissionsSubmissionNanoidDelete$Params {
  siteNanoid: string;
  submissionNanoid: string;
}

export function apiSitesSiteNanoidSubmissionsSubmissionNanoidDelete(http: HttpClient, rootUrl: string, params: ApiSitesSiteNanoidSubmissionsSubmissionNanoidDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiSitesSiteNanoidSubmissionsSubmissionNanoidDelete.PATH, 'delete');
  if (params) {
    rb.path('siteNanoid', params.siteNanoid, {});
    rb.path('submissionNanoid', params.submissionNanoid, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiSitesSiteNanoidSubmissionsSubmissionNanoidDelete.PATH = '/api/sites/{siteNanoid}/submissions/{submissionNanoid}';
