// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Webly.Data;

#nullable disable

namespace Webly.Data.Migrations
{
    [DbContext(typeof(WeblyDbContext))]
    [Migration("20260921001800_RefreshTokenReplacedAt")]
    partial class RefreshTokenReplacedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Webly.Data.Models.Authentication.ExternalLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderKey")
                        .IsUnique();

                    b.ToTable("ExternalLogins");
                });

            modelBuilder.Entity("Webly.Data.Models.Authentication.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReplacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Webly.Data.Models.Authentication.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CurrentSiteId")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nanoid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Roles")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurrentSiteId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Nanoid")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Webly.Data.Models.Authentication.UserSecurityToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("UserSecurityTokens");
                });

            modelBuilder.Entity("Webly.Data.Models.Chat.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nanoid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Nanoid")
                        .IsUnique();

                    b.HasIndex("SiteId")
                        .IsUnique()
                        .HasDatabaseName("IX_Conversations_OneActivePerSite")
                        .HasFilter("\"Status\" = 'Active'");

                    b.HasIndex("UserId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Webly.Data.Models.Chat.ConversationMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nanoid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Parts")
                        .HasColumnType("jsonb");

                    b.Property<int?>("ProducedVersionId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nanoid")
                        .IsUnique();

                    b.HasIndex("ProducedVersionId");

                    b.HasIndex("ConversationId", "Sequence")
                        .IsUnique();

                    b.ToTable("ConversationMessages");
                });

            modelBuilder.Entity("Webly.Data.Models.Deployments.Deployment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nanoid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderDeploymentId")
                        .HasColumnType("text");

                    b.Property<string>("ProviderUrl")
                        .HasColumnType("text");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.Property<int>("SiteVersionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TriggeredByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Nanoid")
                        .IsUnique();

                    b.HasIndex("SiteVersionId");

                    b.HasIndex("TriggeredByUserId");

                    b.HasIndex("SiteId", "CreatedAt");

                    b.ToTable("Deployments");
                });

            modelBuilder.Entity("Webly.Data.Models.Sites.Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DnsRecordName")
                        .HasColumnType("text");

                    b.Property<string>("DnsRecordType")
                        .HasColumnType("text");

                    b.Property<string>("DnsRecordValue")
                        .HasColumnType("text");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("Nanoid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderDomainId")
                        .HasColumnType("text");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Hostname")
                        .IsUnique();

                    b.HasIndex("Nanoid")
                        .IsUnique();

                    b.HasIndex("SiteId")
                        .IsUnique()
                        .HasDatabaseName("IX_Domains_OnePrimaryPerSite")
                        .HasFilter("\"IsPrimary\"");

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("Webly.Data.Models.Sites.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("HeadVersionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nanoid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderProjectId")
                        .HasColumnType("text");

                    b.Property<int?>("PublishedVersionId")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HeadVersionId");

                    b.HasIndex("Nanoid")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.HasIndex("PublishedVersionId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("Webly.Data.Models.Sites.SiteVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChangedFileCount")
                        .HasColumnType("integer");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("Nanoid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentVersionId")
                        .HasColumnType("integer");

                    b.Property<int?>("RestoredFromVersionId")
                        .HasColumnType("integer");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.Property<int?>("SourceMessageId")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Nanoid")
                        .IsUnique();

                    b.HasIndex("ParentVersionId");

                    b.HasIndex("RestoredFromVersionId");

                    b.HasIndex("SourceMessageId");

                    b.HasIndex("SiteId", "CommitSha")
                        .IsUnique();

                    b.HasIndex("SiteId", "CreatedAt");

                    b.ToTable("SiteVersions");
                });

            modelBuilder.Entity("Webly.Data.Models.Authentication.ExternalLogin", b =>
                {
                    b.HasOne("Webly.Data.Models.Authentication.User", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Webly.Data.Models.Authentication.RefreshToken", b =>
                {
                    b.HasOne("Webly.Data.Models.Authentication.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Webly.Data.Models.Authentication.User", b =>
                {
                    b.HasOne("Webly.Data.Models.Sites.Site", "CurrentSite")
                        .WithMany()
                        .HasForeignKey("CurrentSiteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentSite");
                });

            modelBuilder.Entity("Webly.Data.Models.Authentication.UserSecurityToken", b =>
                {
                    b.HasOne("Webly.Data.Models.Authentication.User", "User")
                        .WithMany("SecurityTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Webly.Data.Models.Chat.Conversation", b =>
                {
                    b.HasOne("Webly.Data.Models.Sites.Site", "Site")
                        .WithMany("Conversations")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webly.Data.Models.Authentication.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Site");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Webly.Data.Models.Chat.ConversationMessage", b =>
                {
                    b.HasOne("Webly.Data.Models.Chat.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webly.Data.Models.Sites.SiteVersion", "ProducedVersion")
                        .WithMany()
                        .HasForeignKey("ProducedVersionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Conversation");

                    b.Navigation("ProducedVersion");
                });

            modelBuilder.Entity("Webly.Data.Models.Deployments.Deployment", b =>
                {
                    b.HasOne("Webly.Data.Models.Sites.Site", "Site")
                        .WithMany("Deployments")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webly.Data.Models.Sites.SiteVersion", "SiteVersion")
                        .WithMany()
                        .HasForeignKey("SiteVersionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Webly.Data.Models.Authentication.User", "TriggeredBy")
                        .WithMany()
                        .HasForeignKey("TriggeredByUserId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Site");

                    b.Navigation("SiteVersion");

                    b.Navigation("TriggeredBy");
                });

            modelBuilder.Entity("Webly.Data.Models.Sites.Domain", b =>
                {
                    b.HasOne("Webly.Data.Models.Sites.Site", "Site")
                        .WithMany("Domains")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Webly.Data.Models.Sites.Site", b =>
                {
                    b.HasOne("Webly.Data.Models.Sites.SiteVersion", "HeadVersion")
                        .WithMany()
                        .HasForeignKey("HeadVersionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Webly.Data.Models.Authentication.User", "Owner")
                        .WithMany("Sites")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webly.Data.Models.Sites.SiteVersion", "PublishedVersion")
                        .WithMany()
                        .HasForeignKey("PublishedVersionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("HeadVersion");

                    b.Navigation("Owner");

                    b.Navigation("PublishedVersion");
                });

            modelBuilder.Entity("Webly.Data.Models.Sites.SiteVersion", b =>
                {
                    b.HasOne("Webly.Data.Models.Authentication.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("Webly.Data.Models.Sites.SiteVersion", "ParentVersion")
                        .WithMany()
                        .HasForeignKey("ParentVersionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Webly.Data.Models.Sites.SiteVersion", "RestoredFromVersion")
                        .WithMany()
                        .HasForeignKey("RestoredFromVersionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Webly.Data.Models.Sites.Site", "Site")
                        .WithMany("Versions")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webly.Data.Models.Chat.ConversationMessage", "SourceMessage")
                        .WithMany()
                        .HasForeignKey("SourceMessageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("ParentVersion");

                    b.Navigation("RestoredFromVersion");

                    b.Navigation("Site");

                    b.Navigation("SourceMessage");
                });

            modelBuilder.Entity("Webly.Data.Models.Authentication.User", b =>
                {
                    b.Navigation("ExternalLogins");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SecurityTokens");

                    b.Navigation("Sites");
                });

            modelBuilder.Entity("Webly.Data.Models.Chat.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Webly.Data.Models.Sites.Site", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("Deployments");

                    b.Navigation("Domains");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
