/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MessageRole } from '../models/message-role';
export interface ChatMessageResponse {
  createdAt: string;
  nanoid: string;
  producedVersionNanoid?: string | null;
  role: MessageRole;
  text: string;
}
