/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChatMessageResponse } from '../models/chat-message-response';
export interface ConversationResponse {
  activeRunId?: string | null;
  messages: Array<ChatMessageResponse>;
  nanoid: string;
  title?: string | null;
}
