/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DeploymentStatus } from '../models/deployment-status';
export interface DeploymentResponse {
  createdAt: string;
  error?: string | null;
  errorDetail?: string | null;
  finishedAt?: string | null;
  nanoid: string;
  providerUrl?: string | null;
  siteVersionNanoid: string;
  siteVersionSummary: string;
  status: DeploymentStatus;
}
