/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DeploymentStatus } from './deployment-status';

/**
 * Each possible value of `DeploymentStatus`
 */
export const DEPLOYMENT_STATUS: DeploymentStatus[] = [
  'Queued',
  'Preparing',
  'Building',
  'Ready',
  'Failed',
  'Cancelled'
];