/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DomainVerificationState } from './domain-verification-state';

/**
 * Each possible value of `DomainVerificationState`
 */
export const DOMAIN_VERIFICATION_STATE: DomainVerificationState[] = [
  'Pending',
  'Verified',
  'Failed'
];