/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DomainVerificationState } from '../models/domain-verification-state';
export interface DomainResponse {
  dnsRecordName?: string | null;
  dnsRecordType?: string | null;
  dnsRecordValue?: string | null;
  hostname: string;
  isPrimary: boolean;
  lastError?: string | null;
  nanoid: string;
  verificationState: DomainVerificationState;
  verifiedAt?: string | null;
}
