/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FormFieldResponse } from '../models/form-field-response';
export interface FormSubmissionResponse {
  createdAt: string;
  fields: Array<FormFieldResponse>;
  formName: string;
  nanoid: string;
  readAt?: string | null;
}
