/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { JsonNodeOptions } from '../models/json-node-options';
export interface JsonNode {
  options?: JsonNodeOptions;
  parent?: JsonNode;
  root?: JsonNode;
}
