/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MeResponse {
  currentSiteName?: string | null;
  currentSiteNanoid?: string | null;
  displayName?: string | null;
  email?: string | null;
  emailVerified?: boolean;
  hasPassword?: boolean;
  hasSite?: boolean;
  isAuthenticated: boolean;
  linkedProviders?: Array<string>;
  nanoid?: string | null;
  profilePictureUrl?: string | null;
  roles?: Array<string>;
}
