/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MessageRole } from './message-role';

/**
 * Each possible value of `MessageRole`
 */
export const MESSAGE_ROLE: MessageRole[] = [
  'User',
  'Assistant',
  'Tool',
  'System'
];