/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RunKind } from './run-kind';

/**
 * Each possible value of `RunKind`
 */
export const RUN_KIND: RunKind[] = [
  'Chat',
  'Deploy'
];