/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RunEventType } from './run-event-type';

/**
 * Each possible value of `RunEventType`
 */
export const RUN_EVENT_TYPE: RunEventType[] = [
  'TextDelta',
  'MessageCompleted',
  'Activity',
  'FileChanged',
  'WorkspaceProgress',
  'VersionCommitted',
  'BuildFailed',
  'TypesFailed',
  'DeploymentProgress',
  'Completed',
  'Failed'
];