/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type RunEventType = 'TextDelta' | 'MessageCompleted' | 'Activity' | 'FileChanged' | 'WorkspaceProgress' | 'WorkspaceReady' | 'VersionCommitted' | 'BuildFailed' | 'TypesFailed' | 'DeploymentProgress' | 'Completed' | 'Failed';

