/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RunKind } from '../models/run-kind';
export interface RunSubscription {
  isLive?: boolean;
  lastSeq?: number;
  runId?: string;
  runKind?: RunKind;
}
