/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RunEventType } from '../models/run-event-type';
export interface RunEvent {
  createdAt?: string;
  detail?: string | null;
  error?: string | null;
  text?: string | null;
  type: RunEventType;
  versionNanoid?: string | null;
}
