/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SiteVersionOrigin } from '../models/site-version-origin';
export interface SiteVersionResponse {
  changedFileCount: number;
  commitSha: string;
  createdAt: string;
  details?: string | null;
  isHead: boolean;
  isPublished: boolean;
  nanoid: string;
  origin: SiteVersionOrigin;
  restoredFromNanoid?: string | null;
  summary: string;
}
