/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DomainResponse } from '../models/domain-response';
import { SiteSummaryResponse } from '../models/site-summary-response';
import { SiteVersionResponse } from '../models/site-version-response';
export interface SiteDetailResponse {
  domains?: Array<DomainResponse>;
  headVersion: SiteVersionResponse;
  publishedVersion?: SiteVersionResponse;
  summary: SiteSummaryResponse;
  workspaceReady: boolean;
}
