/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SiteSummaryResponse {
  addressReadyAt?: string | null;
  hasUnpublishedChanges: boolean;
  liveUrl?: string | null;
  name: string;
  nanoid: string;
  publishedAt?: string | null;
  slug: string;
  updatedAt: string;
  url: string;
  weblyUrl: string;
}
