/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SiteVersionOrigin } from './site-version-origin';

/**
 * Each possible value of `SiteVersionOrigin`
 */
export const SITE_VERSION_ORIGIN: SiteVersionOrigin[] = [
  'Template',
  'Agent',
  'Manual',
  'Restore',
  'Upload'
];