/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SiteImageResponse } from '../models/site-image-response';
export interface UploadImagesResponse {
  images: Array<SiteImageResponse>;
  versionNanoid?: string | null;
}
