/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UsageTotalsResponse {
  cacheReadTokens: number;
  cacheWriteTokens: number;
  inputTokens: number;
  modelCostUsd: number;
  outputTokens: number;
  sandboxCostUsd: number;
  sandboxSeconds: number;
  turns: number;
  unfinishedTurns: number;
}
