/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UsageSiteResponse {
  modelCostUsd: number;
  ownerEmail: string;
  sandboxCostUsd: number;
  sandboxSeconds: number;
  siteName: string;
  siteNanoid?: string | null;
  turns: number;
}
