/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UsageUserResponse {
  displayName: string;
  email: string;
  modelCostUsd: number;
  sandboxCostUsd: number;
  sandboxSeconds: number;
  turns: number;
  userNanoid: string;
}
