/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UsageOutcome } from './usage-outcome';

/**
 * Each possible value of `UsageOutcome`
 */
export const USAGE_OUTCOME: UsageOutcome[] = [
  'Completed',
  'Failed',
  'Stopped'
];