/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UsageDayResponse } from '../models/usage-day-response';
import { UsageSiteResponse } from '../models/usage-site-response';
import { UsageTotalsResponse } from '../models/usage-totals-response';
import { UsageTurnResponse } from '../models/usage-turn-response';
import { UsageUserResponse } from '../models/usage-user-response';
export interface UsageReportResponse {
  byDay: Array<UsageDayResponse>;
  bySite: Array<UsageSiteResponse>;
  byUser: Array<UsageUserResponse>;
  periodDays: number;
  recentTurns: Array<UsageTurnResponse>;
  sandboxCostPerHour: number;
  since: string;
  totals: UsageTotalsResponse;
}
