/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UsageOutcome } from '../models/usage-outcome';
export interface UsageTurnResponse {
  agent?: string | null;
  cacheReadTokens: number;
  cacheWriteTokens: number;
  costUsd: number;
  createdAt: string;
  description?: string | null;
  durationMs: number;
  inputTokens: number;
  model?: string | null;
  nanoid: string;
  outcome: UsageOutcome;
  outputTokens: number;
  ownerEmail: string;
  siteName: string;
  siteNanoid?: string | null;
}
