/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UsageReportResponse } from '../../models/usage-report-response';

export interface ApiAdminUsageGet$Plain$Params {
  days?: number;
}

export function apiAdminUsageGet$Plain(http: HttpClient, rootUrl: string, params?: ApiAdminUsageGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<UsageReportResponse>> {
  const rb = new RequestBuilder(rootUrl, apiAdminUsageGet$Plain.PATH, 'get');
  if (params) {
    rb.query('days', params.days, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UsageReportResponse>;
    })
  );
}

apiAdminUsageGet$Plain.PATH = '/api/admin/usage';
