import { ImageResponse } from 'next/og';
import { siteName, siteUrl } from '@/site';

/**
 * The picture that appears when somebody shares a link to this site.
 *
 * Without one, a link pasted into a message or a post is a bare grey rectangle with a URL under it, which is
 * how a real business's website ends up looking like a broken link. Generated by the build rather than drawn
 * by hand, so it carries *this* site's name and colour and needs no designer and no upload.
 *
 * It is type on a colour, deliberately. The alternative is a stock photograph of a building nobody works in,
 * and a name a friend can read at the size a phone shows a link preview is worth more than a picture of
 * something that is not this business. Replace the whole file when there is a real photograph worth putting
 * in front of a link.
 *
 * `alt`, `size` and `contentType` are Next's file conventions and the default export is the image. Note what
 * Next writes: a file called `opengraph-image`, with **no extension**, which a static host has to be willing
 * to serve as a PNG.
 */

// Next treats a generated image as a route, and a route in a static export has to say it is static. Without
// this the build fails outright with "export const dynamic = force-static not configured", which is clear
// enough as messages go, but only once you have seen it.
export const dynamic = 'force-static';

export const alt = siteName;
export const size = { width: 1200, height: 630 };
export const contentType = 'image/png';

/**
 * This site's brand colour, as a **hex** — the one place in this project it is written that way.
 *
 * The card is drawn at build time by Satori, which has no CSS engine: no variables to read, and `oklch()` is
 * refused outright. Webly writes this one line when the site is created, from the same numbers it writes into
 * `look.css`, so change both together.
 *
 * A named constant rather than the colour inline, and that is not style: the card has more than one colour in
 * it, and a rewrite matching "a background that is a hex" painted the white rule brand-coloured on a brand
 * background — an element that was still there and could not be seen. One name, one line, nothing ambiguous.
 */
const brand = '#3b5bd4';

export default function OpenGraphImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          padding: '90px',
          background: brand,
          color: '#ffffff',
        }}
      >
        {/* A rule rather than a logo. It gives the type something to sit against, and it cannot be wrong
            about a business the way an invented mark would be. */}
        <div style={{ display: 'flex', width: '96px', height: '10px', borderRadius: '5px', background: '#ffffff' }} />

        <div style={{ display: 'flex', marginTop: '36px', fontSize: '92px', letterSpacing: '-0.03em' }}>
          {siteName}
        </div>

        {/* Where it is, when the build was told — a preview of a link is one of the few places somebody reads
            a domain on purpose. Left out entirely when there is no address rather than printed as a guess. */}
        {siteUrl && (
          <div style={{ display: 'flex', marginTop: '24px', fontSize: '34px', opacity: 0.75 }}>
            {siteUrl.replace(/^https?:\/\//, '')}
          </div>
        )}
      </div>
    ),
    size,
  );
}
