/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MeResponse } from '../../models/me-response';
import { ResetPasswordRequest } from '../../models/reset-password-request';

export interface ApiAuthPasswordResetPost$Json$Params {
      body?: ResetPasswordRequest
}

export function apiAuthPasswordResetPost$Json(http: HttpClient, rootUrl: string, params?: ApiAuthPasswordResetPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<MeResponse>> {
  const rb = new RequestBuilder(rootUrl, apiAuthPasswordResetPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MeResponse>;
    })
  );
}

apiAuthPasswordResetPost$Json.PATH = '/api/auth/password/reset';
