/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SiteFileResponse } from '../../models/site-file-response';

export interface ApiSitesNanoidFileGet$Plain$Params {
  nanoid: string;
  path?: string;
  version?: string;
}

export function apiSitesNanoidFileGet$Plain(http: HttpClient, rootUrl: string, params: ApiSitesNanoidFileGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<SiteFileResponse>> {
  const rb = new RequestBuilder(rootUrl, apiSitesNanoidFileGet$Plain.PATH, 'get');
  if (params) {
    rb.path('nanoid', params.nanoid, {});
    rb.query('path', params.path, {});
    rb.query('version', params.version, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SiteFileResponse>;
    })
  );
}

apiSitesNanoidFileGet$Plain.PATH = '/api/sites/{nanoid}/file';
