/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SiteDetailResponse } from '../../models/site-detail-response';

export interface ApiSitesNanoidGet$Json$Params {
  nanoid: string;
}

export function apiSitesNanoidGet$Json(http: HttpClient, rootUrl: string, params: ApiSitesNanoidGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<SiteDetailResponse>> {
  const rb = new RequestBuilder(rootUrl, apiSitesNanoidGet$Json.PATH, 'get');
  if (params) {
    rb.path('nanoid', params.nanoid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SiteDetailResponse>;
    })
  );
}

apiSitesNanoidGet$Json.PATH = '/api/sites/{nanoid}';
