/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WakeWorkspaceResponse } from '../../models/wake-workspace-response';

export interface ApiSitesNanoidWorkspacePost$Json$Params {
  nanoid: string;
}

export function apiSitesNanoidWorkspacePost$Json(http: HttpClient, rootUrl: string, params: ApiSitesNanoidWorkspacePost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<WakeWorkspaceResponse>> {
  const rb = new RequestBuilder(rootUrl, apiSitesNanoidWorkspacePost$Json.PATH, 'post');
  if (params) {
    rb.path('nanoid', params.nanoid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WakeWorkspaceResponse>;
    })
  );
}

apiSitesNanoidWorkspacePost$Json.PATH = '/api/sites/{nanoid}/workspace';
