/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SiteFileEntryResponse } from '../../models/site-file-entry-response';

export interface ApiSitesNanoidFilesGet$Json$Params {
  nanoid: string;
  version?: string;
}

export function apiSitesNanoidFilesGet$Json(http: HttpClient, rootUrl: string, params: ApiSitesNanoidFilesGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SiteFileEntryResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiSitesNanoidFilesGet$Json.PATH, 'get');
  if (params) {
    rb.path('nanoid', params.nanoid, {});
    rb.query('version', params.version, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SiteFileEntryResponse>>;
    })
  );
}

apiSitesNanoidFilesGet$Json.PATH = '/api/sites/{nanoid}/files';
