/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SiteVersionResponse } from '../../models/site-version-response';

export interface ApiSitesNanoidVersionsVersionNanoidGet$Json$Params {
  nanoid: string;
  versionNanoid: string;
}

export function apiSitesNanoidVersionsVersionNanoidGet$Json(http: HttpClient, rootUrl: string, params: ApiSitesNanoidVersionsVersionNanoidGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<SiteVersionResponse>> {
  const rb = new RequestBuilder(rootUrl, apiSitesNanoidVersionsVersionNanoidGet$Json.PATH, 'get');
  if (params) {
    rb.path('nanoid', params.nanoid, {});
    rb.path('versionNanoid', params.versionNanoid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SiteVersionResponse>;
    })
  );
}

apiSitesNanoidVersionsVersionNanoidGet$Json.PATH = '/api/sites/{nanoid}/versions/{versionNanoid}';
