/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SiteVersionResponse } from '../../models/site-version-response';

export interface ApiSitesNanoidVersionsGet$Json$Params {
  nanoid: string;
  skip?: number;
  take?: number;
}

export function apiSitesNanoidVersionsGet$Json(http: HttpClient, rootUrl: string, params: ApiSitesNanoidVersionsGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SiteVersionResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiSitesNanoidVersionsGet$Json.PATH, 'get');
  if (params) {
    rb.path('nanoid', params.nanoid, {});
    rb.query('skip', params.skip, {});
    rb.query('take', params.take, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SiteVersionResponse>>;
    })
  );
}

apiSitesNanoidVersionsGet$Json.PATH = '/api/sites/{nanoid}/versions';
