/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateSiteRequest } from '../../models/create-site-request';
import { SiteSummaryResponse } from '../../models/site-summary-response';

export interface ApiSitesPost$Plain$Params {
      body?: CreateSiteRequest
}

export function apiSitesPost$Plain(http: HttpClient, rootUrl: string, params?: ApiSitesPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<SiteSummaryResponse>> {
  const rb = new RequestBuilder(rootUrl, apiSitesPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SiteSummaryResponse>;
    })
  );
}

apiSitesPost$Plain.PATH = '/api/sites';
