/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SiteSummaryResponse } from '../../models/site-summary-response';

export interface ApiSitesGet$Json$Params {
}

export function apiSitesGet$Json(http: HttpClient, rootUrl: string, params?: ApiSitesGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SiteSummaryResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiSitesGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SiteSummaryResponse>>;
    })
  );
}

apiSitesGet$Json.PATH = '/api/sites';
