/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExternalProvidersResponse } from '../../models/external-providers-response';

export interface ApiAuthProvidersGet$Plain$Params {
}

export function apiAuthProvidersGet$Plain(http: HttpClient, rootUrl: string, params?: ApiAuthProvidersGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ExternalProvidersResponse>> {
  const rb = new RequestBuilder(rootUrl, apiAuthProvidersGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExternalProvidersResponse>;
    })
  );
}

apiAuthProvidersGet$Plain.PATH = '/api/auth/providers';
