/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DeploymentResponse } from '../../models/deployment-response';

export interface ApiSitesSiteNanoidDeploymentsPost$Plain$Params {
  siteNanoid: string;
}

export function apiSitesSiteNanoidDeploymentsPost$Plain(http: HttpClient, rootUrl: string, params: ApiSitesSiteNanoidDeploymentsPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DeploymentResponse>> {
  const rb = new RequestBuilder(rootUrl, apiSitesSiteNanoidDeploymentsPost$Plain.PATH, 'post');
  if (params) {
    rb.path('siteNanoid', params.siteNanoid, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DeploymentResponse>;
    })
  );
}

apiSitesSiteNanoidDeploymentsPost$Plain.PATH = '/api/sites/{siteNanoid}/deployments';
