/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MeResponse } from '../../models/me-response';
import { VerifyEmailCodeRequest } from '../../models/verify-email-code-request';

export interface ApiAuthEmailVerifyCodePost$Plain$Params {
      body?: VerifyEmailCodeRequest
}

export function apiAuthEmailVerifyCodePost$Plain(http: HttpClient, rootUrl: string, params?: ApiAuthEmailVerifyCodePost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<MeResponse>> {
  const rb = new RequestBuilder(rootUrl, apiAuthEmailVerifyCodePost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MeResponse>;
    })
  );
}

apiAuthEmailVerifyCodePost$Plain.PATH = '/api/auth/email/verify-code';
